name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    
    steps:
      - uses: lowlighter/metrics@latest
        
        with:   
          plugin_introduction: yes
          plugin_languages: yes
          plugin_notable: yes
          plugin_isocalendar: yes
          plugin_lines: yes
          
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          token: ${{ secrets.TOKEN }}
